# Copyright 2022 Siemens AG
# This file is subject to the terms and conditions of the MIT License.  
# See LICENSE file in the top-level directory

version: "2.4"

services:
    custom-connector:
        image: custom-connector:1.0.0
        build:
            context: ./src
        mem_limit: 100mb
        restart: unless-stopped
        volumes:
            - './publish/:/publish/'
            - './cfg-data/:/cfg-data/'
        networks:
            - proxy-redirect
    ie_databus: # note that the underscore will be removed in the future
        image: eclipse-mosquitto
        mem_limit: 100mb
        networks:
            - proxy-redirect
networks:
    proxy-redirect:
        external: true
        name: proxy-redirect
